import { Inter } from "next/font/google";
import "./globals.css";
import AssignmentProvider from "@/context/assignmentContext";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Assignment Submission System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AssignmentProvider>
          <Navbar />

          {children}
        </AssignmentProvider>
      </body>
    </html>
  );
}
